/**
 * Build-time script: Fetch gallery photos from Google Drive API v3.
 *
 * Usage:
 *   GOOGLE_DRIVE_API_KEY=your_key npm run build:photos
 *
 * This script:
 * 1. Lists all image files in the shared Drive folder
 * 2. Generates src/lib/data/gallery-photos.ts with the photo data
 * 3. Falls back to empty array if the API call fails (folder may be empty)
 *
 * Run this before `npm run build` to include Drive photos in the static site.
 */

import { writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';

const API_KEY = process.env.GOOGLE_DRIVE_API_KEY;
const FOLDER_ID = '1lYNRwhI8HTnjMQr3hvNgF2JEZn806FFt';
const OUTPUT_PATH = resolve(import.meta.dirname, '../src/lib/data/gallery-photos.ts');

interface DriveFile {
	id: string;
	name: string;
	mimeType: string;
}

interface GalleryPhoto {
	id: string;
	thumbnailUrl: string;
	fullUrl: string;
	alt: string;
	width: number;
	height: number;
}

async function fetchDriveFiles(): Promise<DriveFile[]> {
	if (!API_KEY) {
		console.warn('⚠️  GOOGLE_DRIVE_API_KEY not set. Skipping Drive fetch.');
		return [];
	}

	const allFiles: DriveFile[] = [];
	let pageToken: string | undefined;

	do {
		const params = new URLSearchParams({
			q: `'${FOLDER_ID}' in parents and (mimeType contains 'image/')`,
			fields: 'nextPageToken,files(id,name,mimeType)',
			pageSize: '100',
			key: API_KEY
		});

		if (pageToken) {
			params.set('pageToken', pageToken);
		}

		const url = `https://www.googleapis.com/drive/v3/files?${params}`;
		const response = await fetch(url);

		if (!response.ok) {
			const error = await response.text();
			throw new Error(`Drive API error (${response.status}): ${error}`);
		}

		const data = await response.json() as {
			files?: DriveFile[];
			nextPageToken?: string;
		};

		if (data.files) {
			allFiles.push(...data.files);
		}

		pageToken = data.nextPageToken;
	} while (pageToken);

	return allFiles;
}

function generatePhotoData(files: DriveFile[]): GalleryPhoto[] {
	return files.map((file, index) => {
		const safeName = file.name
			.replace(/\.(jpg|jpeg|png|gif|webp|heic|heif)$/i, '')
			.replace(/[_-]/g, ' ')
			.trim();

		return {
			id: file.id,
			thumbnailUrl: `https://drive.google.com/thumbnail?id=${file.id}&sz=w400-h400`,
			fullUrl: `https://drive.google.com/thumbnail?id=${file.id}&sz=w1200`,
			alt: safeName || `Photo ${index + 1}`,
			width: 800,
			height: 600
		};
	});
}

function ensureDir(path: string) {
	const dir = dirname(path);
	if (!existsSync(dir)) {
		mkdirSync(dir, { recursive: true });
	}
}

async function main() {
	console.log('📸 Fetching gallery photos from Google Drive...');
	console.log(`   Folder ID: ${FOLDER_ID}`);

	let photos: GalleryPhoto[];

	try {
		const files = await fetchDriveFiles();
		console.log(`   Found ${files.length} image file(s)`);

		photos = generatePhotoData(files);
	} catch (err) {
		console.error('❌ Failed to fetch from Drive:', err instanceof Error ? err.message : err);
		console.log('   Generating empty gallery (photos can be added later)');
		photos = [];
	}

	const content = `// ⚠️ This file is auto-generated by \`npm run build:photos\`.
// Do not edit manually. Re-run the script after uploading photos to Drive.
// Source folder: https://drive.google.com/drive/folders/${FOLDER_ID}

import type { GalleryPhoto } from './gallery';

export const GALLERY_PHOTOS: GalleryPhoto[] = ${JSON.stringify(photos, null, '\t')};
`;

	ensureDir(OUTPUT_PATH);
	writeFileSync(OUTPUT_PATH, content, 'utf-8');
	console.log(`✅ Generated ${OUTPUT_PATH}`);
	console.log(`   ${photos.length} photo(s)`);
}

main().catch((err) => {
	console.error('❌ Script failed:', err);
	process.exit(1);
});
