/**
 * Auto-generate sitemap.xml from the SvelteKit route tree.
 *
 * Scans src/routes/ for +page.svelte files, generates proper XML
 * with hreflang alternates, and writes to static/sitemap.xml.
 *
 * Run: npx tsx scripts/generate-sitemap.ts
 * Or via: npm run generate-sitemap
 */

import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

// ── Configuration ──────────────────────────────────────────
const __dirname = fileURLToPath(new URL('.', import.meta.url));
const PROJECT_ROOT = join(__dirname, '..');
const ROUTES_DIR = join(PROJECT_ROOT, 'src', 'routes');
const OUTPUT_PATH = join(PROJECT_ROOT, 'static', 'sitemap.xml');

const SITE_URL = 'https://hrishi.org.in';

/** Directories to exclude from the sitemap (e.g., admin, api, error pages) */
const EXCLUDE_DIRS = new Set(['admin', 'api']);

/** File patterns that indicate a route should be included */
const PAGE_FILE = '+page.svelte';

/**
 * Per-route overrides for changefreq and priority.
 * Keys are route paths (e.g., '/venue'), values override defaults.
 */
const ROUTE_CONFIG: Record<string, { changefreq: string; priority: string }> = {
	'/':      { changefreq: 'weekly',  priority: '1.0' },
	'/venue': { changefreq: 'monthly', priority: '0.8' },
	'/rsvp':  { changefreq: 'monthly', priority: '0.9' },
	'/gallery': { changefreq: 'weekly',  priority: '0.7' },
	'/blessings': { changefreq: 'monthly', priority: '0.6' },
};

/** Default values when no route-specific config is found */
const DEFAULT_CHANGEFREQ = 'monthly';
const DEFAULT_PRIORITY = '0.5';

// ── Helpers ────────────────────────────────────────────────

function isExcluded(relativePath: string): boolean {
	const parts = relativePath.split(sep);
	return parts.some((part) => EXCLUDE_DIRS.has(part));
}

function xmlEscape(str: string): string {
	return str
		.replaceAll('&', '&amp;')
		.replaceAll('<', '&lt;')
		.replaceAll('>', '&gt;')
		.replaceAll('"', '&quot;')
		.replaceAll("'", '&apos;');
}

// ── Scan routes ────────────────────────────────────────────

interface RouteEntry {
	/** The route path, e.g. '/' or '/venue' */
	path: string;
	/** The file system path relative to src/routes */
	fsPath: string;
}

function scanRoutes(dir: string, basePath = ''): RouteEntry[] {
	const entries: RouteEntry[] = [];
	let items: string[];

	try {
		items = readdirSync(dir);
	} catch {
		return entries;
	}

	for (const item of items) {
		const fullPath = join(dir, item);
		const relativePath = basePath ? `${basePath}/${item}` : item;

		// Skip excluded directories
		if (EXCLUDE_DIRS.has(item)) continue;

		const stats = statSync(fullPath);

		if (stats.isDirectory()) {
			// Recurse into subdirectories
			entries.push(...scanRoutes(fullPath, relativePath));
		} else if (stats.isFile() && item === PAGE_FILE) {
			// Found a +page.svelte — determine the route path
			const routeDir = relativePath.replace(/\/?\+page\.svelte$/, '');

			// If the directory name is the route itself, use it
			// Otherwise, it's the root route
			let routePath: string;
			if (routeDir === '' || routeDir === '.') {
				routePath = '/';
			} else {
				routePath = '/' + routeDir.split(sep).join('/');
			}

			entries.push({ path: routePath, fsPath: routeDir });
		}
	}

	return entries;
}

// ── Generate XML ───────────────────────────────────────────

function generateSitemapXml(routes: RouteEntry[]): string {
	const lines: string[] = [];

	lines.push(
		'<?xml version="1.0" encoding="UTF-8"?>',
		'<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
		'\t\txmlns:xhtml="http://www.w3.org/1999/xhtml">',
		'\t<!--',
		'\t\tAuto-generated by scripts/generate-sitemap.ts',
		'\t\tDo not edit manually — changes will be overwritten.',
		'\t-->',
		''
	);

	// Sort routes: home first, then alphabetical
	const sorted = [...routes].sort((a, b) => {
		if (a.path === '/') return -1;
		if (b.path === '/') return 1;
		return a.path.localeCompare(b.path);
	});

	for (const route of sorted) {
		const loc = route.path === '/' ? SITE_URL : `${SITE_URL}${route.path}/`;
		const escapedLoc = xmlEscape(loc);

		const config = ROUTE_CONFIG[route.path] ?? {
			changefreq: DEFAULT_CHANGEFREQ,
			priority: DEFAULT_PRIORITY,
		};

		lines.push(
			'\t<url>',
			`\t\t<loc>${escapedLoc}</loc>`,
			`\t\t<xhtml:link rel="alternate" hreflang="mr" href="${escapedLoc}" />`,
			`\t\t<xhtml:link rel="alternate" hreflang="en" href="${escapedLoc}" />`,
			`\t\t<xhtml:link rel="alternate" hreflang="x-default" href="${escapedLoc}" />`,
			`\t\t<changefreq>${config.changefreq}</changefreq>`,
			`\t\t<priority>${config.priority}</priority>`,
			'\t</url>'
		);
		lines.push('');
	}

	lines.push('</urlset>', '');

	return lines.join('\n');
}

// ── Main ───────────────────────────────────────────────────

function main() {
	console.log('🔍 Scanning routes in:', ROUTES_DIR);

	const routes = scanRoutes(ROUTES_DIR);

	if (routes.length === 0) {
		console.warn('⚠️  No routes found. Skipping sitemap generation.');
		return;
	}

	console.log(`📄 Found ${routes.length} public route(s):`);
	for (const route of routes) {
		console.log(`   ${route.path}`);
	}

	const xml = generateSitemapXml(routes);
	writeFileSync(OUTPUT_PATH, xml, 'utf-8');

	console.log(`✅ Sitemap written to: ${OUTPUT_PATH}`);
	console.log(`   ${routes.length} URL(s) generated`);
}

main();
