// ⚠️ This file is auto-generated by `npm run build:photos`.
// Do not edit manually. Re-run the script after uploading photos to Drive.
// Source folder: https://drive.google.com/drive/folders/1lYNRwhI8HTnjMQr3hvNgF2JEZn806FFt

import type { GalleryPhoto } from './gallery';

export const GALLERY_PHOTOS: GalleryPhoto[] = [
	{
		"id": "12nuNBwOORiqj-y323Hywnl5N6ojdZwdp",
		"thumbnailUrl": "https://drive.google.com/thumbnail?id=12nuNBwOORiqj-y323Hywnl5N6ojdZwdp&sz=w400-h400",
		"fullUrl": "https://drive.google.com/thumbnail?id=12nuNBwOORiqj-y323Hywnl5N6ojdZwdp&sz=w1200",
		"alt": "Engagement celebration photo 1",
		"width": 800,
		"height": 600
	},
	{
		"id": "1d7rVgsp4Dxm_gen-7sa9Gq3WcG_Kvl--",
		"thumbnailUrl": "https://drive.google.com/thumbnail?id=1d7rVgsp4Dxm_gen-7sa9Gq3WcG_Kvl--&sz=w400-h400",
		"fullUrl": "https://drive.google.com/thumbnail?id=1d7rVgsp4Dxm_gen-7sa9Gq3WcG_Kvl--&sz=w1200",
		"alt": "Engagement celebration photo 2",
		"width": 800,
		"height": 600
	}
];
